language: node_js
node_js:
  - 8

cache:
  directories:
  - node_modules

before_install:
  - echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
install:
  - npm install

stages:
  - test
  - release

jobs:
  include:
  - stage: test
    script:
    - npm run lint:nofix
    - npm run test:unit
  - stage: release
    before_script:
    - echo VUE_APP_DEBUG=1 > .env
    - echo BASE_URL=/alerta/ > .env
    script: npm run build
    before_deploy:
    - tar cvfz alerta-webui.tar.gz dist/*
    deploy:
    - provider: releases
      skip-cleanup: true
      api_key: "$GITHUB_TOKEN"
      file:
        - alerta-webui.tar.gz
      on:
        tags: true
