name: CI Tests

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Lint
        id: lint
        run: npm run lint:nofix
      - name: Unit Test
        id: unit-test
        run: npm run test:unit

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
